name: continuous Integration

on: 
  push: 
    branches:
      - master

  workflow_dispatch:

env: 
  DOTNET_VERSION: '6.0.X'
    
jobs:
  build:
    runs-on: windows-latest
          
    steps:
      - name: checkout code
        run: action/newwebapp@master

      - name: set up dotnet 6
        run: action/setup-dotnet@v2
                  
      - name: building
        run: dotnet build --configuration Release

      - name: download dependency
        run: dotnet restore
