name: continuous Integration

on: 
  push: 
    branches:
      - master

  workflow_dispatch:

env: 
  DOTNET_VERSION: '6.0.x'
    
jobs:
  build:
    runs-on: windows-latest
          
    steps:
      - name: checkout code
        uses: actions/checkout@master

      - name: set up dotnet 6
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
                  
      - name: building
        run: dotnet build -c Release --no-restore

      - name: download dependency
        run: dotnet restore
